name: devchat
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # nostr_sdk: ^0.0.1
  nostr: ^1.4.0
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.35.5
  flutter_reactive_ble: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
